version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env_non_dev
    volumes:
      - .:/var/lib/postgresql/data/

  app:
    container_name: app
    build:
      context: .
    env_file:
      - .env-non-dev
    ports:
      - 8000:8000
    depends_on:
      db

  volumes:
    db_data:




